export const CLIENTS_LIST_REQUEST     = 'CLIENTS_LIST_REQUEST';
export const CLIENTS_LIST_SUCCESS     = 'CLIENTS_LIST_SUCCESS';
export const CLIENTS_LIST_FAIL        = 'CLIENTS_LIST_FAIL';
export const CLIENTS_LIST_ADD         = 'CLIENTS_LIST_ADD';
export const CLIENTS_LIST_UPDATE      = 'CLIENTS_LIST_UPDATE';
export const CLIENTS_LIST_REMOVE      = 'CLIENTS_LIST_REMOVE';
export const CLIENTS_LIST_FLAG_DELETE = 'CLIENTS_LIST_FLAG_DELETE';
export const CLIENTS_SET_FILTER       = 'CLIENTS_SET_FILTER';
