export const PREFERENCE_FETCH_REQUEST = 'PREFERENCE_FETCH_REQUEST';
export const PREFERENCE_FETCH_SUCCESS = 'PREFERENCE_FETCH_SUCCESS';
export const PREFERENCE_FETCH_FAIL = 'PREFERENCE_FETCH_FAIL';

export const PREFERENCE_UPDATE_REQUEST = 'PREFERENCE_UPDATE_REQUEST';
export const PREFERENCE_UPDATE_SUCCESS = 'PREFERENCE_UPDATE_SUCCESS';
export const PREFERENCE_UPDATE_FAIL = 'PREFERENCE_UPDATE_FAIL';
