export const PROJECTS_LIST_REQUEST    = 'PROJECTS_LIST_REQUEST';
export const PROJECTS_LIST_SUCCESS    = 'PROJECTS_LIST_SUCCESS';
export const PROJECTS_LIST_FAIL       = 'PROJECTS_LIST_FAIL';
export const PROJECTS_LIST_ADD        = 'PROJECTS_LIST_ADD';
export const PROJECTS_LIST_UPDATE     = 'PROJECTS_LIST_UPDATE';
export const PROJECTS_LIST_REMOVE     = 'PROJECTS_LIST_REMOVE';
export const PROJECTS_SET_STATUS_FILTER = 'PROJECTS_SET_STATUS_FILTER';
