export const SUB_TASKS_FETCH_REQUEST = 'SUB_TASKS_FETCH_REQUEST';
export const SUB_TASKS_FETCH_SUCCESS = 'SUB_TASKS_FETCH_SUCCESS';
export const SUB_TASKS_FETCH_FAIL    = 'SUB_TASKS_FETCH_FAIL';
export const SUB_TASKS_ADD           = 'SUB_TASKS_ADD';
export const SUB_TASKS_UPDATE        = 'SUB_TASKS_UPDATE';
export const SUB_TASKS_REMOVE        = 'SUB_TASKS_REMOVE';
